name: Gradle Package

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Show current directory
        run: pwd

      - name: List files in the current directory
        run: ls -la

      - name: Display settings.gradle
        run: cat settings.gradle

      - name: Display build.gradle
        run: cat build.gradle

      - name: Display projects
        run: ./gradlew projects

      - name: Build with Gradle
        run: ./gradlew clean build --info

      - name: Publish to GitHub Packages
        run: ./gradlew publishAll --info
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}